### ISSUE TITLE
[kvm-qemu.sh] Unable to start virt-manager

### ISSUE THREAD

**Issue by QuentainS** [doomedraven/Tools#41]
# Expected Behavior

Be able to run the virt-manager after the execution of the kvm-qemu.sh script.

# Current Behavior

When I run the virt-manager, an error occurs.

## Steps to Reproduce

1. Fresh install of Ubuntu 18.04 LTS
2. apt update && apt upgrade
3. Run "sudo ./kvm-qemu.sh all" script (from the [CAPEv2 repo](https://github.com/kevoreilly/CAPEv2))
4. Reboot (asked by the script)
5. Run the virt-manager

## Context

Ubuntu 18.04 is contained in a VMware VM.

## Failure Logs

```
Error starting Virtual Machine Manager: g-invoke-error-quark: Could not locate gvir_init: libvirt-glib-1.0.so.0: cannot open shared object file: No such file or directory (1)

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/virtmanager.py", line 336, in runcli
    main()
  File "/usr/share/virt-manager/virtManager/virtmanager.py", line 317, in main
    LibvirtGLib.init(None)
GLib.GError: g-invoke-error-quark: Could not locate gvir_init: libvirt-glib-1.0.so.0: cannot open shared object file: No such file or directory (1)
```

**Comment by doomedraven** [comment]
hello, what about instalation log? as it says `| tee -a x.log`? another one you can try `ldd` command described here for another library https://github.com/doomedraven/Tools/issues/33

on my ubuntu 20.04  is in `locate libvirt-glib-1.0.so.0`
```
/usr/local/lib/libvirt-glib-1.0.so.0
/usr/local/lib/libvirt-glib-1.0.so.0.1000.0
```

**Comment by QuentainS** [comment]
Thank you for the quick answer !

Here is the log file from the installation script.
[x.log](https://github.com/doomedraven/Tools/files/4846429/x.log)

**Comment by doomedraven** [comment]
so you not even read the log, you have a lot of fails and dependency problem, your answer is in the log, so try to figurate why you have dependency conflicts

**Comment by QuentainS** [comment]
I saw that there were some dependencies problems. But I just don't understand why there are. This is a fresh installation, I thought the script would work, this is why I made an issue...
Anyway, I apologize for that. I'll try to fix the problem

**Comment by doomedraven** [comment]
I tested it last last week on fully updated ubuntu 20, you are welcome to
investigate and share your findings, as till next big upgrade i dont have
time to test it

**Comment by doomedraven** [comment]
fixed, that is 3rd part library as always, they are such pain in the ass... anyway, couldn't work anymore on 18.04, so use 20.04, thanks for headups

**Comment by QuentainS** [comment]
Problem solved with your fix, tested on 20.04. Damn, I finally got the virt-manager up and running ! Thanks

**Comment by QuentainS** [comment]
Just, maybe you forgot to put a "-y" on the 'apt install' line 265 ?

**Comment by doomedraven** [comment]
265? that is the key there no instlal

**Comment by QuentainS** [comment]
No ;) The line 265 is this one : 
`sudo apt install erlang`

There is no '-y' parameter so we must hit enter during the execution :/

**Comment by doomedraven** [comment]
ah i was looking on cape2.sh not kvm, thanks
